### ISSUE TITLE
Add Topik - Field clear/reset semua setelah press tombol Submit

### ISSUE THREAD

**Issue by ardiansyah-sweng** [ardiansyah-sweng/thesis#120]
**Deskripsi**
Ketika ada salah satu field tidak valid, kemudian press Submit, maka field kosong semua, termasuk yang telah diisi. Seharusnya field yang sudah diisi tadi tidak di-clear, namun tetap berisi nilai yang telah diisi sebelumnya.

**Langkah-langkah**
1. Isi field untuk add topik
2. Sisakan salah satu field tidak valid
3. Klik Submit
4. Terlihat form validation muncul, tapi semua field jadi clear/kosong/reset

**Hasil yang semestinya**
Form validation muncul, tapi field yang sudah diisi dengan benar tidak terclear/reset/kosong.

**Screenshots**
Isi form field
![image](https://user-images.githubusercontent.com/71623245/95424185-7b9df700-096c-11eb-871a-80c5f4e483a6.png)

Setelah tombol Submit diklik, semua field ter-clear/reset/kosong
![image](https://user-images.githubusercontent.com/71623245/95423468-53fa5f00-096b-11eb-9778-a274cfe72cff.png)

Seharusnya, yang sudah diisi tadi tetap muncul dengan tetap menampilkan pesan validasi errornya
![image](https://user-images.githubusercontent.com/71623245/95423507-65dc0200-096b-11eb-9fec-5fbd39847cde.png)

**Comment by muhnashir** [comment]
oke pak, nanti saya tinggal kasih valuenya
