### ISSUE TITLE
Add Topik - Sort daftar topik

### ISSUE THREAD

**Issue by ardiansyah-sweng** [ardiansyah-sweng/thesis#121]
Tolong disorting ya mas @muhnashir , menjadi ascending aja
![image](https://user-images.githubusercontent.com/71623245/95424991-c8360200-096d-11eb-85e9-b6a5211c730d.png)

**Comment by muhnashir** [comment]
ini sudah di sortir berdasarkan id nya pak

**Comment by ardiansyah-sweng** [comment]
> ini sudah di sortir berdasarkan id nya pak

maksud saya disorting ascending berdasarkan nama topiknya mas. Atau di tabel nama kolomnya namanya **topik_bidang**

**Comment by muhnashir** [comment]
![Screenshot 2020-10-08 231033](https://user-images.githubusercontent.com/59910535/95485228-a3687b80-09bb-11eb-97fb-435b87c3745f.png)

**Comment by muhnashir** [comment]
kalau disini saya buat asc malah dari kalimat yang paling banyak dulu pak yang muncul, maka saya buat dsc biar topiknya munculnya dari yang paling pendek kalimatnya

**Comment by muhnashir** [comment]
![Screenshot 2020-10-08 231240](https://user-images.githubusercontent.com/59910535/95485448-f2161580-09bb-11eb-8d58-d906ccb932ec.png)

**Comment by muhnashir** [comment]
ini hasil dari orderBy descending pak
