### ISSUE TITLE
Login - Tampilkan nama sesuai NIPY-nya masing-masing

### ISSUE THREAD

**Issue by ardiansyah-sweng** [ardiansyah-sweng/thesis#123]
Mas @Andikariski tolong nama default Alexander Pierce diganti sesuai nama Dosen yang login sesuai NIPY masing-masing ya...
Jadi kalau yg login NIPY 030 berarti yg tampil adalah **Ardiansyah**, dst...
![image](https://user-images.githubusercontent.com/71623245/95425795-08e24b00-096f-11eb-900b-70b712587b73.png)

**Comment by Andikariski** [comment]
Baik pak
