### ISSUE TITLE
Hamburger menu tidak aktif

### ISSUE THREAD

**Issue by ardiansyah-sweng** [ardiansyah-sweng/thesis#144]
Biasanya kalo diklik page menjadi lebar, skrng ketika diklik tidak berubah mas @muhnashir 
![image](https://user-images.githubusercontent.com/71623245/95985141-6c2c1b80-0e4e-11eb-8912-561ccf01942c.png)

**Comment by muhnashir** [comment]
![Screenshot 2020-10-14 190624](https://user-images.githubusercontent.com/59910535/95986575-70593880-0e50-11eb-9621-77eab5b984bf.png)

**Comment by muhnashir** [comment]
oiya pak tadi malah saya nambahi itu, lupa saya hapus, karena di atas sudah ada pak, jadi yang line 120 dan 121 di file master.blade.php cukup di hapus
