### ISSUE TITLE
Vew page ambil/mendaftar topik TA belum sesuai yang diharapkan

### ISSUE THREAD

**Issue by ardiansyah-sweng** [ardiansyah-sweng/thesis#162]
Mas @LianEx view page yg saya maksud itu persis seperti di hamalan dosen kayak gini
![image](https://user-images.githubusercontent.com/71623245/96537912-93a53d00-12c1-11eb-93f8-cf48084d099e.png)

Bedanya nanti ada di kolom2nya saja. Nah kolom ini bisa dilihat buku [Analisis kebutuhan](https://docs.google.com/document/d/1I6T8nZhpnuYm-cz_VL2hTvjSWB3Qo8Pm0IszQOaPwCc/edit?usp=sharing).
Baca terutama di bagian US5 - User Story – Mengambil topik tugas akhir pada Wireframe dan Workflow. Cermati aja tampilan2 yg diharapkan di sana.

Harap diperbaiki ya....

**Comment by andiii-sa** [comment]
maaf pak, sepertinya saya salah mengerjakan.
harusnya saya bikin page mendaftar, bukan yang daftar.
akan saya perbaiki pak.

**Comment by ardiansyah-sweng** [comment]
> maaf pak, sepertinya saya salah mengerjakan.
> harusnya saya bikin page mendaftar, bukan yang daftar.
> akan saya perbaiki pak.

sudah benar kok. karena kalau mau mendaftar harus membuka page daftar topik TA dulu

**Comment by andiii-sa** [comment]
baik pak
