### ISSUE TITLE
Message flash Ikon x exit tidak ada

### ISSUE THREAD

**Issue by ardiansyah-sweng** [ardiansyah-sweng/thesis#163]
Setelah berhasil edit topik TA, setelah keluar message flash, tidak ada ikon X untuk exit seperti biasanya mas @Andikariski 
![image](https://user-images.githubusercontent.com/71623245/96538424-b3893080-12c2-11eb-93aa-4debd8c95758.png)

Ditambahkan ya...

**Comment by Andikariski** [comment]
oh iya pak, saya edit dlu
