### ISSUE TITLE
Profile pic tidak tampil

### ISSUE THREAD

**Issue by ardiansyah-sweng** [ardiansyah-sweng/thesis#87]
Gambar profile di bagian Direct Chat pada dashboard adminLTE

**Expected behavior**
Seharusnya gambar profile muncul

**Screenshots**
![image](https://user-images.githubusercontent.com/71623245/94497502-9d3b0800-0221-11eb-9f91-19842145f09f.png)

**Comment by muhnashir** [comment]
oalah ok pak saya perbaiki
